package stconv

import (
	"bytes"
	"encoding/binary"
	"math"
	"math/rand"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// The 2-shard fixture under testdata/multi (repo root, two levels up from
// this package) is generated by testdata/gen's multi mode:
//
//	go run ./testdata/gen multi testdata/multi
//
// Layout (dataStart = 8 + padded header length, per shard):
//
//	shard 1 (model.safetensors-00001-of-00002.safetensors), dataStart 192:
//	  model.layers.0.mlp.up_proj.weight    BF16 [2,4]  in-shard [0,16)
//	  model.layers.0.self_attn.q_proj.weight F16 [2,2] in-shard [16,24)
//	shard 2 (model.safetensors-00002-of-00002.safetensors), dataStart 184:
//	  model.layers.0.input_layernorm.weight F16 [4]    in-shard [0,8)
//	  model.layers.0.mlp.position_ids       I32 [4]    in-shard [8,16)
const (
	multiShard1 = "model.safetensors-00001-of-00002.safetensors"
	multiShard2 = "model.safetensors-00002-of-00002.safetensors"

	fixtureDir      = "../../testdata/multi"
	shard1DataStart = 192
	shard2DataStart = 184

	nameUpProj = "model.layers.0.mlp.up_proj.weight"
	nameQProj  = "model.layers.0.self_attn.q_proj.weight"
	nameNorm   = "model.layers.0.input_layernorm.weight"
	namePosIDs = "model.layers.0.mlp.position_ids"
)

// multiShardPaths returns the committed fixture paths in shard order.
func multiShardPaths() []string {
	return []string{
		filepath.Join(fixtureDir, multiShard1),
		filepath.Join(fixtureDir, multiShard2),
	}
}

// The 2-shard fixture under testdata/multirot is generated by
// testdata/gen's multirot mode: one 256-element tensor per shard (both
// multiples of the ConvRot group size of 256), so every tensor converts
// instead of skipping:
//
//	shard 1: rot.a BF16 [128,2] (128 rows; rotation groups straddle rows)
//	shard 2: rot.b F16  [2,128] (2 rows)
const (
	rotFixtureDir = "../../testdata/multirot"
	rotA          = "rot.a"
	rotB          = "rot.b"
)

// rotShardPaths returns the committed multirot fixture paths in shard
// order (the shard filenames match the multi fixture's).
func rotShardPaths() []string {
	return []string{
		filepath.Join(rotFixtureDir, multiShard1),
		filepath.Join(rotFixtureDir, multiShard2),
	}
}

// outEntry is one expected output header entry.
type outEntry struct {
	name  string
	dtype DType
	off   [2]int64
}

func checkOutHeader(t *testing.T, h *Header, want []outEntry) {
	t.Helper()
	if len(h.Tensors) != len(want) {
		t.Fatalf("output header has %d tensors, want %d", len(h.Tensors), len(want))
	}
	for i, w := range want {
		e := h.Tensors[i]
		if e.Name != w.name || e.Info.DType != w.dtype || e.Info.DataOffsets != w.off {
			t.Errorf("output header[%d] = %s %s %v, want %s %s %v",
				i, e.Name, e.Info.DType, e.Info.DataOffsets, w.name, w.dtype, w.off)
		}
	}
}

func TestPlanModelTwoShards(t *testing.T) {
	plans, outHeader, err := planModel(ConvertOptions{
		InputShards: multiShardPaths(),
		Default:     TargetNone,
	})
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}

	// Global tensor order: shard order, then in-shard header order.
	// Source offsets stay relative to each tensor's own shard file.
	want := []struct {
		name  string
		shard int
		off   int64
		len   int64
	}{
		{nameUpProj, 0, shard1DataStart + 0, 16},
		{nameQProj, 0, shard1DataStart + 16, 8},
		{nameNorm, 1, shard2DataStart + 0, 8},
		{namePosIDs, 1, shard2DataStart + 8, 16},
	}
	if len(plans) != len(want) {
		t.Fatalf("got %d plans, want %d", len(plans), len(want))
	}
	for i, w := range want {
		p := plans[i]
		if p.name != w.name {
			t.Errorf("plan[%d].name = %q, want %q", i, p.name, w.name)
		}
		if p.srcShard != w.shard {
			t.Errorf("plan[%d] (%s).srcShard = %d, want %d", i, w.name, p.srcShard, w.shard)
		}
		if p.srcAbsOffset != w.off {
			t.Errorf("plan[%d] (%s).srcAbsOffset = %d, want %d", i, w.name, p.srcAbsOffset, w.off)
		}
		if p.srcLen != w.len {
			t.Errorf("plan[%d] (%s).srcLen = %d, want %d", i, w.name, p.srcLen, w.len)
		}
		if p.skippedWhy == "" {
			t.Errorf("plan[%d] (%s): TargetNone should passthrough, got a conversion", i, w.name)
		}
	}

	// Output offsets accumulate globally across shards, in the same order.
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeBF16, [2]int64{0, 16}},
		{nameQProj, DTypeF16, [2]int64{16, 24}},
		{nameNorm, DTypeF16, [2]int64{24, 32}},
		{namePosIDs, DTypeI32, [2]int64{32, 48}},
	})
}

func TestPlanModelTargetsAcrossShards(t *testing.T) {
	plans, outHeader, err := planModel(ConvertOptions{
		InputShards: multiShardPaths(),
		Default:     TargetFP8E4M3,
		MinElems:    5,
	})
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}

	want := []struct {
		name  string
		dtype DType
		skip  bool
	}{
		{nameUpProj, DTypeF8E4M3, false}, // 8 elems >= 5 -> converted
		{nameQProj, DTypeF16, true},      // 4 elems < 5  -> kept
		{nameNorm, DTypeF16, true},       // 4 elems < 5  -> kept (shard 2)
		{namePosIDs, DTypeI32, true},     // non-float    -> kept
	}
	if len(plans) != len(want) {
		t.Fatalf("got %d plans, want %d", len(plans), len(want))
	}
	for i, w := range want {
		p := plans[i]
		if p.name != w.name {
			t.Fatalf("plan[%d].name = %q, want %q", i, p.name, w.name)
		}
		if p.outDType != w.dtype {
			t.Errorf("plan[%d] (%s).outDType = %s, want %s", i, w.name, p.outDType, w.dtype)
		}
		if (p.skippedWhy != "") != w.skip {
			t.Errorf("plan[%d] (%s).skippedWhy = %q, want skipped=%v", i, w.name, p.skippedWhy, w.skip)
		}
	}

	// The converted tensor shrinks to 1 byte/elem, passthrough keeps its
	// size, and offsets keep accumulating across the shard boundary.
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeF8E4M3, [2]int64{0, 8}},
		{nameQProj, DTypeF16, [2]int64{8, 16}},
		{nameNorm, DTypeF16, [2]int64{16, 24}},
		{namePosIDs, DTypeI32, [2]int64{24, 40}},
	})
}

// singleFixturePath is the committed 1-file gen fixture (testdata/gen's
// single mode): up_proj (BF16 [2,4], 8 elems), q_proj (F16 [2,2]), norm
// (F16 [4]).
const singleFixturePath = "../../testdata/single/single.safetensors"

// TestConvertSingleFP8DefaultProtection runs the single fixture through
// ConvertFile with the default fp8 target and protection enabled (no
// config): the norm weight is kept at its original dtype with the
// protection reason in the report, the attention projection is kept (the
// fp8 rule), and the plain MLP projection still converts to fp8.
func TestConvertSingleFP8DefaultProtection(t *testing.T) {
	out := filepath.Join(t.TempDir(), "out.safetensors")
	stats, err := ConvertFile(ConvertOptions{
		InputPath:  singleFixturePath,
		OutputPath: out,
		Default:    TargetFP8E4M3,
		Protect:    true,
	})
	if err != nil {
		t.Fatalf("ConvertFile: %v", err)
	}
	if len(stats) != 3 {
		t.Fatalf("got %d stats, want 3", len(stats))
	}

	want := []struct {
		name       string
		toDType    DType
		skippedWhy string
	}{
		{nameUpProj, DTypeF8E4M3, ""},
		{nameQProj, DTypeF16, protectReasonAttnProj},
		{nameNorm, DTypeF16, protectReasonNorms},
	}
	for i, w := range want {
		s := stats[i]
		if s.Name != w.name {
			t.Fatalf("stat[%d].Name = %q, want %q", i, s.Name, w.name)
		}
		if s.ToDType != w.toDType {
			t.Errorf("stat (%s).ToDType = %s, want %s", s.Name, s.ToDType, w.toDType)
		}
		if s.SkippedWhy != w.skippedWhy {
			t.Errorf("stat (%s).SkippedWhy = %q, want %q", s.Name, s.SkippedWhy, w.skippedWhy)
		}
	}

	// The protected tensors are passthrough: output dtype equals input
	// dtype (without protection the norm would be F8_E4M3).
	for _, s := range stats[1:] {
		if s.ToDType != s.FromDType {
			t.Errorf("stat (%s): protected tensor converted %s -> %s, want passthrough", s.Name, s.FromDType, s.ToDType)
		}
	}
}

// TestPlanTensorProtectionOrdering pins that protection is decided before
// the mechanical passthrough checks: with MinElems high enough to skip
// every tensor in the single fixture, the protected tensors still report
// their policy reason while the unprotected one reports the mechanical
// one. A config default (not a rule) is a bulk default, so protection
// applies to it too. Zero-value options (Protect unset) keep the
// pre-policy blanket-conversion behavior.
func TestPlanTensorProtectionOrdering(t *testing.T) {
	t.Run("policy reason wins over min-elems", func(t *testing.T) {
		plans, _, err := planModel(ConvertOptions{
			InputShards: []string{singleFixturePath},
			Default:     TargetFP8E4M3,
			Protect:     true,
			MinElems:    100, // all three fixture tensors are smaller
		})
		if err != nil {
			t.Fatalf("planModel: %v", err)
		}
		wantSkip := map[string]string{
			nameUpProj: "fewer than 100 elements", // not protected
			nameQProj:  protectReasonAttnProj,     // fp8 rule
			nameNorm:   protectReasonNorms,        // hard rule
		}
		for _, p := range plans {
			if p.skippedWhy != wantSkip[p.name] {
				t.Errorf("plan (%s).skippedWhy = %q, want %q", p.name, p.skippedWhy, wantSkip[p.name])
			}
		}
	})

	t.Run("config default is not explicit, protection applies", func(t *testing.T) {
		plans, _, err := planModel(ConvertOptions{
			InputShards: []string{singleFixturePath},
			Config:      &Config{Default: "fp8_e4m3"},
			Protect:     true,
		})
		if err != nil {
			t.Fatalf("planModel: %v", err)
		}
		for _, p := range plans {
			if p.name == nameNorm && p.skippedWhy != protectReasonNorms {
				t.Errorf("plan (%s).skippedWhy = %q, want the protection reason (config default is not explicit intent)", p.name, p.skippedWhy)
			}
			if p.name == nameUpProj && p.skippedWhy != "" {
				t.Errorf("plan (%s).skippedWhy = %q, want converted", p.name, p.skippedWhy)
			}
		}
	})

	t.Run("zero-value options keep the old behavior", func(t *testing.T) {
		plans, _, err := planModel(ConvertOptions{
			InputShards: []string{singleFixturePath},
			Default:     TargetFP8E4M3,
		})
		if err != nil {
			t.Fatalf("planModel (no protect): %v", err)
		}
		for _, p := range plans {
			if p.skippedWhy != "" {
				t.Errorf("plan (%s).skippedWhy = %q, want converted (protection off)", p.name, p.skippedWhy)
			}
		}
	})
}

func TestPlanModelInt8ScaleFollowsOwner(t *testing.T) {
	cfg := &Config{
		Rules: []ConfigRule{{Match: nameNorm, DType: "int8"}},
	}
	plans, outHeader, err := planModel(ConvertOptions{
		InputShards: multiShardPaths(),
		Config:      cfg,
		Default:     TargetNone,
	})
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}

	// Only the config-matched tensor (in shard 2) is converted to int8 and
	// needs a scale sibling.
	for i, p := range plans {
		if p.name == nameNorm && len(p.sibs) == 0 {
			t.Errorf("plan[%d] (%s): int8 plan must need a scale sibling", i, p.name)
		}
		if p.name != nameNorm && len(p.sibs) > 0 {
			t.Errorf("plan[%d] (%s): unexpected scale sibling", i, p.name)
		}
	}

	// The ".scale" sibling lands immediately after its owner in the merged
	// header, and the following tensor's offset accounts for both.
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeBF16, [2]int64{0, 16}},
		{nameQProj, DTypeF16, [2]int64{16, 24}},
		{nameNorm, DTypeI8, [2]int64{24, 28}},
		{nameNorm + ".scale", DTypeF32, [2]int64{28, 32}},
		{namePosIDs, DTypeI32, [2]int64{32, 48}},
	})
}

// TestPlanSiblings pins the sibling spec for every converting target: the
// suffix, dtype, element count, and file order (before/after the owner).
func TestPlanSiblings(t *testing.T) {
	cases := []struct {
		target   TargetKind
		shape    []int64
		numElems int64
		want     []sib
	}{
		{TargetFP8E4M3, []int64{2, 4}, 8, nil},
		{TargetFP8E5M2, []int64{2, 4}, 8, nil},
		{TargetInt8, []int64{2, 4}, 8, []sib{{".scale", DTypeF32, 1, false}}},
		// convrot: rows = shape[0] for a 2-D tensor, one row for a 1-D one.
		{TargetInt8ConvRot, []int64{2, 128}, 256, []sib{{".scale", DTypeF32, 2, true}}},
		{TargetInt8ConvRot, []int64{256}, 256, []sib{{".scale", DTypeF32, 1, true}}},
		{TargetMxFP4, []int64{2, 128}, 256, []sib{{".block_scale", DTypeU8, 8, true}}},
		{TargetMxFP4, []int64{33}, 33, []sib{{".block_scale", DTypeU8, 2, true}}}, // ceil(33/32)
		{TargetNVFP4, []int64{2, 128}, 256, []sib{
			{".global_scale", DTypeF32, 1, true},
			{".block_scale", DTypeF8E4M3, 16, true},
		}},
		{TargetInt4, []int64{2, 4}, 8, []sib{{".scale", DTypeF32, 1, false}}},
		{TargetNone, []int64{2, 4}, 8, nil},
	}
	for _, tc := range cases {
		got := planSiblings(tc.target, tc.shape, tc.numElems)
		if !reflect.DeepEqual(got, tc.want) {
			t.Errorf("planSiblings(%v, %v, %d) = %#v, want %#v", tc.target, tc.shape, tc.numElems, got, tc.want)
		}
	}
}

// planTensorFor plans one synthetic tensor against a given target and
// returns the plan plus the fresh header it emitted into.
func planTensorFor(t *testing.T, target TargetKind, shape []int64) (tensorPlan, *Header) {
	t.Helper()
	var numElems int64 = 1
	for _, d := range shape {
		numElems *= d
	}
	info := TensorInfo{DType: DTypeBF16, Shape: shape, DataOffsets: [2]int64{0, numElems * 2}}
	h := &Header{}
	p, err := planTensor(ConvertOptions{Default: target}, "w", info, 0, 0, h)
	if err != nil {
		t.Fatalf("planTensor(%v): %v", target, err)
	}
	return p, h
}

// TestPlanTensorNewTargetHeaders pins the exact output header entries (order,
// dtype, shape, offsets) for the new targets on a synthetic 256-element
// [2,128] input.
func TestPlanTensorNewTargetHeaders(t *testing.T) {
	shape := []int64{2, 128} // 256 elements

	cases := []struct {
		target TargetKind
		want   []outEntry
	}{
		{
			TargetInt4,
			[]outEntry{
				{"w", DTypeU8, [2]int64{0, 128}},          // 256 elems -> 128 packed bytes
				{"w.scale", DTypeF32, [2]int64{128, 132}}, // scalar F32 after owner
			},
		},
		{
			TargetInt8ConvRot,
			[]outEntry{
				{"w.scale", DTypeF32, [2]int64{0, 8}}, // 2 row scales, before owner
				{"w", DTypeI8, [2]int64{8, 264}},      // 256 I8 bytes
			},
		},
		{
			TargetMxFP4,
			[]outEntry{
				{"w.block_scale", DTypeU8, [2]int64{0, 8}}, // 256/32 = 8 E8M0 bytes, before owner
				{"w", DTypeU8, [2]int64{8, 136}},           // 128 packed bytes
			},
		},
		{
			TargetNVFP4,
			[]outEntry{
				{"w.global_scale", DTypeF32, [2]int64{0, 4}},    // scalar, before owner
				{"w.block_scale", DTypeF8E4M3, [2]int64{4, 20}}, // 256/16 = 16 bytes
				{"w", DTypeU8, [2]int64{20, 148}},               // 128 packed bytes
			},
		},
	}
	for _, tc := range cases {
		p, h := planTensorFor(t, tc.target, shape)
		if p.skippedWhy != "" {
			t.Fatalf("%v: unexpected skip %q", tc.target, p.skippedWhy)
		}
		checkOutHeader(t, h, tc.want)
	}
}

// TestPlanTensorConvRotSkip pins that a convrot target passthrough-skips a
// tensor whose element count is not a multiple of 256, keeping its source
// dtype and full byte length.
func TestPlanTensorConvRotSkip(t *testing.T) {
	shape := []int64{255} // 255 elements, not a multiple of 256
	p, h := planTensorFor(t, TargetInt8ConvRot, shape)
	if p.skippedWhy != "not a multiple of 256 (rotation group size)" {
		t.Fatalf("skippedWhy = %q, want the convrot 256-multiple reason", p.skippedWhy)
	}
	if p.target != TargetNone || len(p.sibs) != 0 {
		t.Errorf("skipped plan should be a passthrough with no siblings, got target=%v sibs=%#v", p.target, p.sibs)
	}
	// Passthrough: source dtype (BF16), full 2-byte/elem length.
	checkOutHeader(t, h, []outEntry{{"w", DTypeBF16, [2]int64{0, 510}}})

	// -min-elems is checked first, so it wins over the convrot 256 rule.
	h2 := &Header{}
	p2, err := planTensor(ConvertOptions{Default: TargetInt8ConvRot, MinElems: 300}, "w",
		TensorInfo{DType: DTypeBF16, Shape: shape, DataOffsets: [2]int64{0, 510}}, 0, 0, h2)
	if err != nil {
		t.Fatalf("planTensor (min-elems): %v", err)
	}
	if p2.skippedWhy != "fewer than 300 elements" {
		t.Fatalf("min-elems must win over the convrot rule, got skippedWhy = %q", p2.skippedWhy)
	}
}

func TestPlanModelSingleShardMatchesPreRefactor(t *testing.T) {
	single, singleHeader, err := planModel(ConvertOptions{
		InputShards: multiShardPaths()[:1],
		Default:     TargetNone,
	})
	if err != nil {
		t.Fatalf("planModel (single): %v", err)
	}
	two, twoHeader, err := planModel(ConvertOptions{
		InputShards: multiShardPaths(),
		Default:     TargetNone,
	})
	if err != nil {
		t.Fatalf("planModel (two): %v", err)
	}

	// A one-shard plan is exactly the first shard's slice of the two-shard
	// plan: same order, srcShard 0, same shard-relative offsets.
	if !reflect.DeepEqual(single, two[:2]) {
		t.Errorf("single-shard plans differ from two-shard prefix:\n single=%#v\n prefix=%#v", single, two[:2])
	}
	wantSingleHeader := &Header{Tensors: twoHeader.Tensors[:2], Metadata: twoHeader.Metadata}
	if !reflect.DeepEqual(singleHeader, wantSingleHeader) {
		t.Errorf("single-shard header differs from two-shard prefix:\n single=%#v\n prefix=%#v", singleHeader, wantSingleHeader)
	}

	// The pinned values below are what ConvertFile's planning produced for
	// this shard before the multi-shard refactor: header entries in input
	// order, original dtypes and sizes, offsets starting at 0.
	checkOutHeader(t, singleHeader, []outEntry{
		{nameUpProj, DTypeBF16, [2]int64{0, 16}},
		{nameQProj, DTypeF16, [2]int64{16, 24}},
	})
	if singleHeader.Metadata != nil {
		t.Errorf("single-shard header metadata = %v, want nil (fixture has none)", singleHeader.Metadata)
	}
}

func TestPlanModelMetadataFromFirstShard(t *testing.T) {
	dir := t.TempDir()
	writeMetaShard(t, filepath.Join(dir, "a.safetensors"), map[string]string{"origin": "a"}, "ta")
	writeMetaShard(t, filepath.Join(dir, "b.safetensors"), map[string]string{"origin": "b"}, "tb")

	_, outHeader, err := planModel(ConvertOptions{
		InputShards: []string{filepath.Join(dir, "a.safetensors"), filepath.Join(dir, "b.safetensors")},
		Default:     TargetNone,
	})
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}
	want := map[string]string{"origin": "a"}
	if !reflect.DeepEqual(outHeader.Metadata, want) {
		t.Errorf("merged metadata = %v, want %v (first shard's block)", outHeader.Metadata, want)
	}
}

// writeMetaShard writes a minimal one-tensor F32 [2] safetensors file with
// the given __metadata__ block; planning tests only need a parseable header.
func writeMetaShard(t *testing.T, path string, metadata map[string]string, name string) {
	t.Helper()
	h := &Header{
		Metadata: metadata,
		Tensors: []TensorEntry{{
			Name: name,
			Info: TensorInfo{DType: DTypeF32, Shape: []int64{2}, DataOffsets: [2]int64{0, 8}},
		}},
	}
	f, err := CreateOutputFile(path, h)
	if err != nil {
		t.Fatalf("CreateOutputFile(%s): %v", path, err)
	}
	if _, err := f.Write(make([]byte, 8)); err != nil {
		t.Fatalf("writing tensor data: %v", err)
	}
	if err := f.Close(); err != nil {
		t.Fatalf("closing %s: %v", path, err)
	}
}

func TestConvertModelTwoShardsFP8(t *testing.T) {
	opts := ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  filepath.Join(t.TempDir(), "fp8.safetensors"),
		Default:     TargetFP8E4M3,
	}
	if _, err := ConvertModel(opts); err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}
	plans, _, err := planModel(opts)
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}

	out, err := os.Open(opts.OutputPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, dataStart, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}

	// Tensor count, order, dtypes, and byte lengths all match the plan:
	// float tensors shrink to 1 byte/elem, the I32 tensor passes through
	// at its original size, offsets contiguous from 0.
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeF8E4M3, [2]int64{0, 8}},
		{nameQProj, DTypeF8E4M3, [2]int64{8, 12}},
		{nameNorm, DTypeF8E4M3, [2]int64{12, 16}},
		{namePosIDs, DTypeI32, [2]int64{16, 32}},
	})

	// Total data byte length equals the sum of the plan's output sizes.
	var total int64
	for _, p := range plans {
		total += p.totalOutLen()
	}
	if got := outHeader.Tensors[len(outHeader.Tensors)-1].Info.DataOffsets[1]; got != total {
		t.Errorf("total data byte length = %d, want %d (sum of planned sizes)", got, total)
	}

	// The file is exactly 8 + header (as written, padded) + data - nothing
	// trailing, nothing missing. dataStart is 8 + the header length.
	fi, err := out.Stat()
	if err != nil {
		t.Fatalf("stat output: %v", err)
	}
	if fi.Size() != dataStart+total {
		t.Errorf("output size = %d, want %d (8 + headerLen %d + data %d)", fi.Size(), dataStart+total, dataStart-8, total)
	}
}

func TestConvertModelTwoShardsInt8(t *testing.T) {
	opts := ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  filepath.Join(t.TempDir(), "int8.safetensors"),
		Default:     TargetInt8,
	}
	stats, err := ConvertModel(opts)
	if err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}

	out, err := os.Open(opts.OutputPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, dataStart, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}

	// Every float tensor converts to int8 and gets a ".scale" sibling
	// immediately after its owner in the merged file; the I32 tensor is
	// copied through and gets no scale.
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeI8, [2]int64{0, 8}},
		{nameUpProj + ".scale", DTypeF32, [2]int64{8, 12}},
		{nameQProj, DTypeI8, [2]int64{12, 16}},
		{nameQProj + ".scale", DTypeF32, [2]int64{16, 20}},
		{nameNorm, DTypeI8, [2]int64{20, 24}},
		{nameNorm + ".scale", DTypeF32, [2]int64{24, 28}},
		{namePosIDs, DTypeI32, [2]int64{28, 44}},
	})

	// Structural check: one scale per converted tensor, each immediately
	// after its int8 owner in merged-file order.
	converted := 0
	for _, s := range stats {
		if s.ToDType == DTypeI8 {
			converted++
		}
	}
	scales := 0
	for i, e := range outHeader.Tensors {
		if !strings.HasSuffix(e.Name, ".scale") {
			continue
		}
		scales++
		owner := e.Name[:len(e.Name)-len(".scale")]
		if i == 0 || outHeader.Tensors[i-1].Name != owner || outHeader.Tensors[i-1].Info.DType != DTypeI8 {
			t.Errorf("%s is not immediately after its int8 owner in the merged header", e.Name)
		}
	}
	if scales != converted {
		t.Errorf("got %d .scale tensors, want %d (one per converted tensor)", scales, converted)
	}

	// Scale values: maxAbs/127 from the fixture's known values (up_proj
	// maxAbs 3.25, q_proj 2.0, norm 1.0).
	readScale := func(name string) float32 {
		t.Helper()
		for _, e := range outHeader.Tensors {
			if e.Name != name {
				continue
			}
			b := make([]byte, 4)
			if _, err := out.ReadAt(b, dataStart+e.Info.DataOffsets[0]); err != nil {
				t.Fatalf("reading scale %s: %v", name, err)
			}
			return math.Float32frombits(binary.LittleEndian.Uint32(b))
		}
		t.Fatalf("scale %s not in output header", name)
		return 0
	}
	wantScales := map[string]float32{
		nameUpProj + ".scale": 3.25 / 127,
		nameQProj + ".scale":  2.0 / 127,
		nameNorm + ".scale":   1.0 / 127,
	}
	for name, want := range wantScales {
		if got := readScale(name); got != want {
			t.Errorf("scale %s = %v, want %v", name, got, want)
		}
	}

	// Quantized data check: norm is all 1.0 with scale 1.0/127, so
	// q = round(1.0/(1.0/127)) = 127 for every element.
	var normOff int64
	for _, e := range outHeader.Tensors {
		if e.Name == nameNorm {
			normOff = e.Info.DataOffsets[0]
		}
	}
	nb := make([]byte, 4)
	if _, err := out.ReadAt(nb, dataStart+normOff); err != nil {
		t.Fatalf("reading norm data: %v", err)
	}
	if !bytes.Equal(nb, []byte{127, 127, 127, 127}) {
		t.Errorf("norm int8 data = %v, want all 127", nb)
	}
}

// f32Tensor is one tensor of a synthetic single-file F32 input.
type f32Tensor struct {
	name string
	vals []float32
}

// writeF32Shard writes a single-file safetensors input containing the
// given F32 tensors, in order, and returns its path.
func writeF32Shard(t *testing.T, tensors ...f32Tensor) string {
	t.Helper()
	h := &Header{}
	var data []byte
	for _, tv := range tensors {
		b := make([]byte, 4*len(tv.vals))
		for i, v := range tv.vals {
			binary.LittleEndian.PutUint32(b[i*4:], math.Float32bits(v))
		}
		h.Tensors = append(h.Tensors, TensorEntry{
			Name: tv.name,
			Info: TensorInfo{
				DType:       DTypeF32,
				Shape:       []int64{int64(len(tv.vals))},
				DataOffsets: [2]int64{int64(len(data)), int64(len(data) + len(b))},
			},
		})
		data = append(data, b...)
	}
	path := filepath.Join(t.TempDir(), "in.safetensors")
	f, err := CreateOutputFile(path, h)
	if err != nil {
		t.Fatalf("CreateOutputFile(%s): %v", path, err)
	}
	if _, err := f.Write(data); err != nil {
		t.Fatalf("writing tensor data: %v", err)
	}
	if err := f.Close(); err != nil {
		t.Fatalf("closing %s: %v", path, err)
	}
	return path
}

// TestConvertInt4Pinned checks the int4 pass end-to-end on a synthetic
// input: exact packed bytes (hand-computed RNE int4), exact scale bytes,
// and the P2 S3 header layout (owner U8, then the F32 ".scale" sibling).
func TestConvertInt4Pinned(t *testing.T) {
	// "w.odd": 5 elements (odd -> trailing zero nibble); 14.0 is the
	// outlier that sets the scale. scale = 14.0/7 = 2.0 (exact).
	// Quotients: 2/2=1 -> 1; -4/2=-2 -> -2; 9/2=4.5 -> 4 (RNE tie to even;
	// half-away rounding would give 5); 14/2=7 -> 7; 0.5/2=0.25 -> 0.
	// Packed (element 2i in the low nibble, two's-complement nibbles):
	//   [1, -2] -> 0xE1; [4, 7] -> 0x74; [0, pad] -> 0x00.
	// "w.scaled": 3 elements; maxAbs 3.25 -> scale 3.25/7 (a non-power-of-
	// two quotient, so the scale bytes are a real check). Quotients:
	// 1/(3.25/7) ~= 2.154 -> 2; 3.25 -> 7; 2 -> 4.308 -> 4.
	// Packed: [2, 7] -> 0x72; [4, pad] -> 0x04.
	in := writeF32Shard(t,
		f32Tensor{name: "w.odd", vals: []float32{2.0, -4.0, 9.0, 14.0, 0.5}},
		f32Tensor{name: "w.scaled", vals: []float32{1.0, 3.25, 2.0}},
	)
	outPath := filepath.Join(t.TempDir(), "out.safetensors")
	stats, err := ConvertFile(ConvertOptions{
		InputPath:  in,
		OutputPath: outPath,
		Default:    TargetInt4,
	})
	if err != nil {
		t.Fatalf("ConvertFile: %v", err)
	}
	if len(stats) != 2 {
		t.Fatalf("got %d stats, want 2", len(stats))
	}

	out, err := os.Open(outPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, dataStart, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}

	// P2 S3 layout: owner (U8, ceil(n/2) bytes) then the F32 ".scale"
	// sibling, contiguous from 0.
	checkOutHeader(t, outHeader, []outEntry{
		{"w.odd", DTypeU8, [2]int64{0, 3}},
		{"w.odd.scale", DTypeF32, [2]int64{3, 7}},
		{"w.scaled", DTypeU8, [2]int64{7, 9}},
		{"w.scaled.scale", DTypeF32, [2]int64{9, 13}},
	})

	readData := func(name string, n int) []byte {
		t.Helper()
		for _, e := range outHeader.Tensors {
			if e.Name != name {
				continue
			}
			b := make([]byte, n)
			if _, err := out.ReadAt(b, dataStart+e.Info.DataOffsets[0]); err != nil {
				t.Fatalf("reading %s: %v", name, err)
			}
			return b
		}
		t.Fatalf("tensor %s not in output header", name)
		return nil
	}

	if got := readData("w.odd", 3); !bytes.Equal(got, []byte{0xE1, 0x74, 0x00}) {
		t.Errorf("w.odd packed bytes = % X, want E1 74 00", got)
	}
	if got := readData("w.scaled", 2); !bytes.Equal(got, []byte{0x72, 0x04}) {
		t.Errorf("w.scaled packed bytes = % X, want 72 04", got)
	}

	// Scale bytes: exact 4-byte little-endian F32 payloads.
	wantScales := map[string]uint32{
		"w.odd.scale":    math.Float32bits(2.0),
		"w.scaled.scale": math.Float32bits(3.25 / 7.0),
	}
	for name, wantBits := range wantScales {
		got := readData(name, 4)
		if !bytes.Equal(got, []byte{byte(wantBits), byte(wantBits >> 8), byte(wantBits >> 16), byte(wantBits >> 24)}) {
			t.Errorf("scale %s bytes = % X, want %08X (LE)", name, got, wantBits)
		}
	}

	// The report carries the same scale.
	if stats[0].Scale != 2.0 {
		t.Errorf("stats[0].Scale = %v, want 2.0", stats[0].Scale)
	}
	if stats[1].Scale != 3.25/7.0 {
		t.Errorf("stats[1].Scale = %v, want %v", stats[1].Scale, 3.25/7.0)
	}
}

// TestConvertInt4DecodedErrorBound checks the dequantization error bound
// |dequant - x| <= scale/2 element-wise on a seeded random tensor, with
// an odd chunk size (3 -> rounded up to 4) so the data pass crosses many
// chunk boundaries. The outlier is 56.0 so the scale is 56/7 = 8.0, a
// power of two: f32 division by 8 and multiplication by 8 are exact, so
// the bound is exact (no f32 rounding slack) and must hold as stated.
func TestConvertInt4DecodedErrorBound(t *testing.T) {
	rnd := rand.New(rand.NewSource(42))
	n := 1001 // odd -> one trailing pad nibble
	vals := make([]float32, n)
	for i := range vals {
		vals[i] = float32(rnd.Float64()*2 - 1)
	}
	vals[123] = 56.0  // positive outlier, sets maxAbs = 56
	vals[456] = -48.0 // negative, well inside the range
	in := writeF32Shard(t, f32Tensor{name: "w", vals: vals})
	outPath := filepath.Join(t.TempDir(), "out.safetensors")
	stats, err := ConvertFile(ConvertOptions{
		InputPath:  in,
		OutputPath: outPath,
		Default:    TargetInt4,
		ChunkElems: 3,
	})
	if err != nil {
		t.Fatalf("ConvertFile: %v", err)
	}
	if stats[0].Scale != 8.0 {
		t.Fatalf("scale = %v, want 8.0 (56/7)", stats[0].Scale)
	}

	scale := stats[0].Scale
	nibbles := unpackNibbles(readTensorBytes(t, outPath, "w"))
	if len(nibbles) != n+1 { // odd count -> one pad nibble
		t.Fatalf("decoded %d nibbles, want %d (incl. pad)", len(nibbles), n+1)
	}
	bad := 0
	for i, x := range vals {
		dq := int4ToF32(nibbles[i], scale)
		if d := math.Abs(float64(dq) - float64(x)); d > float64(scale)/2 {
			if bad < 20 {
				t.Errorf("elem %d (x=%v, deq=%v): |deq - x| = %v > scale/2 = %v", i, x, dq, d, float64(scale)/2)
			}
			bad++
		}
	}
	if bad > 20 {
		t.Errorf("... and %d more elements violate the bound", bad-20)
	}
	if nibbles[n] != 0 {
		t.Errorf("trailing padding nibble = 0x%02x, want 0x00", nibbles[n])
	}
}

// TestConvertModelFP8SpotCheckValues decodes the merged output's first
// tensor and compares it byte-for-byte against a direct float32->fp8
// conversion of the fixture's known input values, fixed in testdata/gen
// (upProjTensor: 0.1, -0.2, 0.3, -0.4, 1.5, -1.5, 3.25, -3.25, stored as
// BF16).
func TestConvertModelFP8SpotCheckValues(t *testing.T) {
	opts := ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  filepath.Join(t.TempDir(), "fp8.safetensors"),
		Default:     TargetFP8E4M3,
	}
	if _, err := ConvertModel(opts); err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}
	known := []float32{0.1, -0.2, 0.3, -0.4, 1.5, -1.5, 3.25, -3.25}

	// Pin the fixture first: the shard's stored BF16 bytes must decode to
	// the BF16-rounded known values, so the check below runs against the
	// documented generator values.
	src, err := os.Open(opts.InputShards[0])
	if err != nil {
		t.Fatalf("opening shard 1: %v", err)
	}
	defer src.Close()
	srcBytes := make([]byte, len(known)*2)
	if _, err := src.ReadAt(srcBytes, shard1DataStart); err != nil {
		t.Fatalf("reading source bytes: %v", err)
	}
	stored := make([]float32, len(known))
	for i, k := range known {
		stored[i] = bf16ToF32(binary.LittleEndian.Uint16(srcBytes[i*2:]))
		if want := bf16ToF32(f32ToBF16(k)); stored[i] != want {
			t.Fatalf("fixture %s[%d] decodes to %v, want %v (generator value %v)", nameUpProj, i, stored[i], want, k)
		}
	}

	// up_proj is the first tensor in the merged output (global order).
	out, err := os.Open(opts.OutputPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, dataStart, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}
	e := outHeader.Tensors[0]
	if e.Name != nameUpProj || e.Info.DType != DTypeF8E4M3 {
		t.Fatalf("first output tensor = %s %s, want %s F8_E4M3", e.Name, e.Info.DType, nameUpProj)
	}
	got := make([]byte, len(known))
	if _, err := out.ReadAt(got, dataStart+e.Info.DataOffsets[0]); err != nil {
		t.Fatalf("reading output bytes: %v", err)
	}
	for i, s := range stored {
		want := f32ToF8E4M3(s)
		if got[i] != want {
			t.Errorf("fp8 byte %d (input %v) = 0x%02x, want 0x%02x", i, s, got[i], want)
		}
	}
}

// TestConvertFileSingleShardGolden pins single-file output bytes against
// goldens produced by the pre-multi-shard-refactor ConvertFile (commit
// 0fcd091): converting the 1-shard gen fixture must be byte-identical
// across the refactor, for both conversion paths and passthrough.
func TestConvertFileSingleShardGolden(t *testing.T) {
	const dir = "../../testdata/single"
	cases := []struct {
		kind   TargetKind
		golden string
	}{
		{TargetFP8E4M3, "golden.fp8_e4m3.safetensors"},
		{TargetInt8, "golden.int8.safetensors"},
		{TargetNone, "golden.none.safetensors"},
	}
	for _, tc := range cases {
		t.Run(tc.golden, func(t *testing.T) {
			want, err := os.ReadFile(filepath.Join(dir, tc.golden))
			if err != nil {
				t.Fatalf("reading golden: %v", err)
			}
			out := filepath.Join(t.TempDir(), "out.safetensors")
			if _, err := ConvertFile(ConvertOptions{
				InputPath:  filepath.Join(dir, "single.safetensors"),
				OutputPath: out,
				Default:    tc.kind,
			}); err != nil {
				t.Fatalf("ConvertFile: %v", err)
			}
			got, err := os.ReadFile(out)
			if err != nil {
				t.Fatalf("reading output: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("output differs from pre-refactor golden: got %d bytes, want %d", len(got), len(want))
			}
		})
	}
}

// TestConvertPackedRoundTripByteIdentical pins that a -target none
// passthrough of one of this tool's own packed 4-bit outputs is
// byte-identical to that output. The packed owners keep their full semantic
// shape in the header while only half the bytes are stored, so passthrough
// must plan the source's stored byte length (srcLen), not dtype-size ×
// numElems, or the re-emitted data_offsets drift past the real data and the
// round-trip file is corrupt.
func TestConvertPackedRoundTripByteIdentical(t *testing.T) {
	const dir = "../../testdata/single"
	for _, tc := range []struct {
		name   string
		target TargetKind
	}{
		{"int4", TargetInt4},
		{"mxfp4", TargetMxFP4},
		{"nvfp4", TargetNVFP4},
	} {
		t.Run(tc.name, func(t *testing.T) {
			first := filepath.Join(t.TempDir(), "quant.safetensors")
			if _, err := ConvertFile(ConvertOptions{
				InputPath:  filepath.Join(dir, "single.safetensors"),
				OutputPath: first,
				Default:    tc.target,
			}); err != nil {
				t.Fatalf("ConvertFile (%s): %v", tc.name, err)
			}
			round := filepath.Join(t.TempDir(), "round.safetensors")
			if _, err := ConvertFile(ConvertOptions{
				InputPath:  first,
				OutputPath: round,
				Default:    TargetNone,
			}); err != nil {
				t.Fatalf("ConvertFile round-trip (%s): %v", tc.name, err)
			}
			want, err := os.ReadFile(first)
			if err != nil {
				t.Fatalf("reading quantized output: %v", err)
			}
			got, err := os.ReadFile(round)
			if err != nil {
				t.Fatalf("reading round-trip output: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("target-none round-trip of %s output differs (%d vs %d bytes)", tc.name, len(got), len(want))
			}
		})
	}
}

func TestConvertModelTwoShardsPassthrough(t *testing.T) {
	opts := ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  filepath.Join(t.TempDir(), "merged.safetensors"),
		Default:     TargetNone,
	}
	stats, err := ConvertModel(opts)
	if err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}
	plans, _, err := planModel(opts)
	if err != nil {
		t.Fatalf("planModel: %v", err)
	}

	// Stats keep global order and carry the source shard filename.
	wantSource := []string{multiShard1, multiShard1, multiShard2, multiShard2}
	if len(stats) != len(wantSource) {
		t.Fatalf("got %d stats, want %d", len(stats), len(wantSource))
	}
	for i, s := range stats {
		if s.Source != wantSource[i] {
			t.Errorf("stat[%d] (%s).Source = %q, want %q", i, s.Name, s.Source, wantSource[i])
		}
		if s.SkippedWhy == "" {
			t.Errorf("stat[%d] (%s): TargetNone should passthrough", i, s.Name)
		}
	}

	// Output header: 4 tensors in global order, contiguous offsets, no
	// metadata (the fixture shards have none).
	out, err := os.Open(opts.OutputPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, dataStart, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}
	if outHeader.Metadata != nil {
		t.Errorf("output metadata = %v, want nil", outHeader.Metadata)
	}
	checkOutHeader(t, outHeader, []outEntry{
		{nameUpProj, DTypeBF16, [2]int64{0, 16}},
		{nameQProj, DTypeF16, [2]int64{16, 24}},
		{nameNorm, DTypeF16, [2]int64{24, 32}},
		{namePosIDs, DTypeI32, [2]int64{32, 48}},
	})

	// Each output tensor's bytes equal its source shard's bytes, and the
	// data block ends exactly at the file size.
	fi, err := out.Stat()
	if err != nil {
		t.Fatalf("stat output: %v", err)
	}
	if fi.Size() != dataStart+48 {
		t.Errorf("output size = %d, want %d (header + 48 data bytes)", fi.Size(), dataStart+48)
	}
	for i, e := range outHeader.Tensors {
		p := plans[i]
		src, err := os.Open(opts.InputShards[p.srcShard])
		if err != nil {
			t.Fatalf("opening shard %d: %v", p.srcShard, err)
		}
		wantBytes := make([]byte, p.srcLen)
		if _, err := src.ReadAt(wantBytes, p.srcAbsOffset); err != nil {
			src.Close()
			t.Fatalf("reading source bytes for %s: %v", p.name, err)
		}
		src.Close()
		gotBytes := make([]byte, p.srcLen)
		if _, err := out.ReadAt(gotBytes, dataStart+e.Info.DataOffsets[0]); err != nil {
			t.Fatalf("reading output bytes for %s: %v", p.name, err)
		}
		if !bytes.Equal(gotBytes, wantBytes) {
			t.Errorf("tensor %s: output bytes differ from source shard bytes", p.name)
		}
	}

	t.Run("single file leaves Source empty", func(t *testing.T) {
		stats, err := ConvertFile(ConvertOptions{
			InputPath:  multiShardPaths()[0],
			OutputPath: filepath.Join(t.TempDir(), "single.safetensors"),
			Default:    TargetNone,
		})
		if err != nil {
			t.Fatalf("ConvertFile: %v", err)
		}
		if len(stats) != 2 {
			t.Fatalf("got %d stats, want 2", len(stats))
		}
		for _, s := range stats {
			if s.Source != "" {
				t.Errorf("stat (%s).Source = %q, want empty for single-file input", s.Name, s.Source)
			}
		}
	})

	t.Run("no input shards", func(t *testing.T) {
		if _, err := ConvertModel(ConvertOptions{OutputPath: t.TempDir()}); err == nil {
			t.Fatal("expected error for empty InputShards")
		}
	})
}

// readTensorBytes returns the raw data bytes of tensor name in the
// safetensors file at path.
func readTensorBytes(t *testing.T, path, name string) []byte {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("opening %s: %v", path, err)
	}
	defer f.Close()
	h, dataStart, err := ReadHeader(f)
	if err != nil {
		t.Fatalf("reading header of %s: %v", path, err)
	}
	for _, e := range h.Tensors {
		if e.Name != name {
			continue
		}
		b := make([]byte, e.Info.DataOffsets[1]-e.Info.DataOffsets[0])
		if _, err := f.ReadAt(b, dataStart+e.Info.DataOffsets[0]); err != nil {
			t.Fatalf("reading %s from %s: %v", name, path, err)
		}
		return b
	}
	t.Fatalf("tensor %s not found in %s", name, path)
	return nil
}

// ownerInIndex returns the input index shard for an output tensor name.
// Sibling tensors (.scale, .block_scale, .global_scale) are not in the
// input index; their shard is their owner's.
func ownerInIndex(t *testing.T, inIdx *Index, name string) string {
	t.Helper()
	if shardName, ok := inIdx.WeightMap[name]; ok {
		return shardName
	}
	for _, suffix := range []string{".global_scale", ".block_scale", ".scale"} {
		if owner := strings.TrimSuffix(name, suffix); owner != name {
			if shardName, ok := inIdx.WeightMap[owner]; ok {
				return shardName
			}
		}
	}
	t.Fatalf("tensor %s and its owner missing from input index", name)
	return ""
}

// readOutShardHeader reads the header of one output shard file.
func readOutShardHeader(t *testing.T, outDir, shardName string) *Header {
	t.Helper()
	f, err := os.Open(filepath.Join(outDir, shardName))
	if err != nil {
		t.Fatalf("opening output shard %s: %v", shardName, err)
	}
	defer f.Close()
	h, _, err := ReadHeader(f)
	if err != nil {
		t.Fatalf("reading output shard %s: %v", shardName, err)
	}
	return h
}

// checkShardsMatchMerged asserts that every tensor in the merged output's
// header has byte-identical data in the sharded output, in the shard the
// input index assigns it to.
func checkShardsMatchMerged(t *testing.T, outDir, mergedPath string, inIdx *Index) {
	t.Helper()
	merged, err := os.Open(mergedPath)
	if err != nil {
		t.Fatalf("opening merged output: %v", err)
	}
	defer merged.Close()
	mergedHeader, mergedDataStart, err := ReadHeader(merged)
	if err != nil {
		t.Fatalf("reading merged header: %v", err)
	}
	for _, e := range mergedHeader.Tensors {
		shardName := ownerInIndex(t, inIdx, e.Name)
		got := readTensorBytes(t, filepath.Join(outDir, shardName), e.Name)
		want := make([]byte, e.Info.DataOffsets[1]-e.Info.DataOffsets[0])
		if _, err := merged.ReadAt(want, mergedDataStart+e.Info.DataOffsets[0]); err != nil {
			t.Fatalf("reading merged bytes for %s: %v", e.Name, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("tensor %s: sharded output bytes differ from merged output", e.Name)
		}
	}
}

func TestConvertModelMultiFileFP8(t *testing.T) {
	inIdx, err := LoadIndex(filepath.Join(fixtureDir, fixtureIndexName))
	if err != nil {
		t.Fatalf("LoadIndex: %v", err)
	}

	outDir := t.TempDir()
	stats, err := ConvertModel(ConvertOptions{
		InputShards: multiShardPaths(),
		InputIndex:  inIdx,
		OutputDir:   outDir,
		Default:     TargetFP8E4M3,
	})
	if err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}

	// The equivalent single merged output, for byte comparison.
	mergedPath := filepath.Join(t.TempDir(), "merged.safetensors")
	if _, err := ConvertModel(ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  mergedPath,
		Default:     TargetFP8E4M3,
	}); err != nil {
		t.Fatalf("ConvertModel (merged): %v", err)
	}

	t.Run("output dir has exactly the 2 shards + index", func(t *testing.T) {
		entries, err := os.ReadDir(outDir)
		if err != nil {
			t.Fatalf("reading output dir: %v", err)
		}
		got := make([]string, 0, len(entries))
		for _, e := range entries {
			got = append(got, e.Name())
		}
		want := []string{multiShard1, multiShard2, fixtureIndexName}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("output dir = %v, want exactly %v", got, want)
		}
	})

	t.Run("shards parse and hold exactly the input's tensors", func(t *testing.T) {
		for _, shardName := range []string{multiShard1, multiShard2} {
			f, err := os.Open(filepath.Join(outDir, shardName))
			if err != nil {
				t.Fatalf("opening output shard %s: %v", shardName, err)
			}
			h, dataStart, err := ReadHeader(f)
			if err != nil {
				f.Close()
				t.Fatalf("reading output shard %s: %v", shardName, err)
			}

			want := make(map[string]bool)
			for name, sn := range inIdx.WeightMap {
				if sn == shardName {
					want[name] = true
				}
			}
			got := make(map[string]bool, len(h.Tensors))
			for _, e := range h.Tensors {
				got[e.Name] = true
			}
			if !reflect.DeepEqual(got, want) {
				t.Errorf("shard %s tensors = %v, want %v (the input's assignment)", shardName, got, want)
			}

			checkContiguous(t, h)
			if h.Metadata != nil {
				t.Errorf("shard %s metadata = %v, want nil (fixture has none)", shardName, h.Metadata)
			}
			// The file is exactly 8 + header + data: nothing trailing.
			fi, err := f.Stat()
			if err != nil {
				f.Close()
				t.Fatalf("stat output shard %s: %v", shardName, err)
			}
			wantSize := dataStart + h.Tensors[len(h.Tensors)-1].Info.DataOffsets[1]
			if fi.Size() != wantSize {
				t.Errorf("shard %s size = %d, want %d (8 + headerLen + data)", shardName, fi.Size(), wantSize)
			}
			f.Close()
		}
	})

	t.Run("data bytes identical to merged output", func(t *testing.T) {
		checkShardsMatchMerged(t, outDir, mergedPath, inIdx)
	})

	t.Run("index matches input assignments and computed total_size", func(t *testing.T) {
		outIdx, err := LoadIndex(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("LoadIndex (output): %v", err)
		}
		if !reflect.DeepEqual(outIdx.WeightMap, inIdx.WeightMap) {
			t.Errorf("output weight_map = %v, want %v (input's assignments)", outIdx.WeightMap, inIdx.WeightMap)
		}
		// total_size equals the sum of (shard size - 8 - headerLen) across
		// shards, i.e. the actual data bytes on disk.
		var total int64
		for _, shardName := range []string{multiShard1, multiShard2} {
			f, err := os.Open(filepath.Join(outDir, shardName))
			if err != nil {
				t.Fatalf("opening output shard %s: %v", shardName, err)
			}
			_, dataStart, err := ReadHeader(f)
			if err != nil {
				f.Close()
				t.Fatalf("reading output shard %s: %v", shardName, err)
			}
			fi, err := f.Stat()
			f.Close()
			if err != nil {
				t.Fatalf("stat output shard %s: %v", shardName, err)
			}
			total += fi.Size() - dataStart
		}
		if got := outIdx.Metadata["total_size"]; got != float64(total) {
			t.Errorf("total_size = %v, want %d (sum of shard data bytes)", got, total)
		}
		// Pinned: up_proj 8 + q_proj 4 + norm 4 + position_ids 16 fp8/passthrough bytes.
		if got := outIdx.Metadata["total_size"]; got != float64(32) {
			t.Errorf("total_size = %v, want 32 (pinned)", got)
		}
	})

	t.Run("weight_map key order matches the input index", func(t *testing.T) {
		inRaw, err := os.ReadFile(filepath.Join(fixtureDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("reading input index: %v", err)
		}
		outRaw, err := os.ReadFile(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("reading output index: %v", err)
		}
		want := weightMapKeyOrder(t, inRaw)
		got := weightMapKeyOrder(t, outRaw)
		if !reflect.DeepEqual(got, want) {
			t.Errorf("output weight_map key order = %v, want %v (input index order)", got, want)
		}
	})

	t.Run("stats carry the source shard", func(t *testing.T) {
		wantSource := []string{multiShard1, multiShard1, multiShard2, multiShard2}
		if len(stats) != len(wantSource) {
			t.Fatalf("got %d stats, want %d", len(stats), len(wantSource))
		}
		for i, s := range stats {
			if s.Source != wantSource[i] {
				t.Errorf("stat[%d] (%s).Source = %q, want %q", i, s.Name, s.Source, wantSource[i])
			}
		}
	})

	t.Run("output dir is a loadable model directory", func(t *testing.T) {
		shards, idx, err := DiscoverShards(outDir)
		if err != nil {
			t.Fatalf("DiscoverShards(outDir): %v", err)
		}
		if idx == nil {
			t.Fatal("expected the written index to drive discovery")
		}
		want := []string{filepath.Join(outDir, multiShard1), filepath.Join(outDir, multiShard2)}
		if !reflect.DeepEqual(shards, want) {
			t.Errorf("discovered shards = %v, want %v", shards, want)
		}
	})
}

func TestConvertModelMultiFileInt8(t *testing.T) {
	inIdx, err := LoadIndex(filepath.Join(fixtureDir, fixtureIndexName))
	if err != nil {
		t.Fatalf("LoadIndex: %v", err)
	}

	outDir := t.TempDir()
	if _, err := ConvertModel(ConvertOptions{
		InputShards: multiShardPaths(),
		InputIndex:  inIdx,
		OutputDir:   outDir,
		Default:     TargetInt8,
	}); err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}

	mergedPath := filepath.Join(t.TempDir(), "merged.safetensors")
	if _, err := ConvertModel(ConvertOptions{
		InputShards: multiShardPaths(),
		OutputPath:  mergedPath,
		Default:     TargetInt8,
	}); err != nil {
		t.Fatalf("ConvertModel (merged): %v", err)
	}

	t.Run("per-shard headers: scales follow owners", func(t *testing.T) {
		shard1, err := os.Open(filepath.Join(outDir, multiShard1))
		if err != nil {
			t.Fatalf("opening output shard 1: %v", err)
		}
		h1, _, err := ReadHeader(shard1)
		shard1.Close()
		if err != nil {
			t.Fatalf("reading output shard 1: %v", err)
		}
		checkOutHeader(t, h1, []outEntry{
			{nameUpProj, DTypeI8, [2]int64{0, 8}},
			{nameUpProj + ".scale", DTypeF32, [2]int64{8, 12}},
			{nameQProj, DTypeI8, [2]int64{12, 16}},
			{nameQProj + ".scale", DTypeF32, [2]int64{16, 20}},
		})

		shard2, err := os.Open(filepath.Join(outDir, multiShard2))
		if err != nil {
			t.Fatalf("opening output shard 2: %v", err)
		}
		h2, _, err := ReadHeader(shard2)
		shard2.Close()
		if err != nil {
			t.Fatalf("reading output shard 2: %v", err)
		}
		checkOutHeader(t, h2, []outEntry{
			{nameNorm, DTypeI8, [2]int64{0, 4}},
			{nameNorm + ".scale", DTypeF32, [2]int64{4, 8}},
			{namePosIDs, DTypeI32, [2]int64{8, 24}},
		})
	})

	t.Run("index: 7 entries, scales in owner's shard, total_size", func(t *testing.T) {
		outIdx, err := LoadIndex(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("LoadIndex (output): %v", err)
		}
		want := map[string]string{
			nameUpProj:            multiShard1,
			nameUpProj + ".scale": multiShard1,
			nameQProj:             multiShard1,
			nameQProj + ".scale":  multiShard1,
			nameNorm:              multiShard2,
			nameNorm + ".scale":   multiShard2,
			namePosIDs:            multiShard2,
		}
		if !reflect.DeepEqual(outIdx.WeightMap, want) {
			t.Errorf("output weight_map = %v, want %v", outIdx.WeightMap, want)
		}
		// Pinned from the plan: 8+4 + 4+4 (shard 1) + 4+4 + 16 (shard 2).
		if got := outIdx.Metadata["total_size"]; got != float64(44) {
			t.Errorf("total_size = %v, want 44 (pinned)", got)
		}
	})

	t.Run("weight_map key order: owners in input order, scales after owners", func(t *testing.T) {
		outRaw, err := os.ReadFile(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("reading output index: %v", err)
		}
		got := weightMapKeyOrder(t, outRaw)
		want := []string{
			nameUpProj, nameUpProj + ".scale",
			nameQProj, nameQProj + ".scale",
			nameNorm, nameNorm + ".scale",
			namePosIDs,
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("output weight_map key order = %v, want %v", got, want)
		}
	})

	t.Run("data bytes identical to merged output", func(t *testing.T) {
		checkShardsMatchMerged(t, outDir, mergedPath, inIdx)
	})
}

// TestConvertModelMultiFileConvRot runs the multirot fixture (two shards,
// one 256-multiple tensor each) through ConvertModel with multi-file
// output: row-scale siblings land before their owners in each shard, the
// per-tensor bytes match the merged output, the index covers owners and
// scales in file order with a summed total_size, and the output dir
// round-trips both through DiscoverShards and a target-none conversion
// that reproduces the merged file byte-for-byte.
func TestConvertModelMultiFileConvRot(t *testing.T) {
	inIdx, err := LoadIndex(filepath.Join(rotFixtureDir, fixtureIndexName))
	if err != nil {
		t.Fatalf("LoadIndex: %v", err)
	}

	outDir := t.TempDir()
	if _, err := ConvertModel(ConvertOptions{
		InputShards: rotShardPaths(),
		InputIndex:  inIdx,
		OutputDir:   outDir,
		Default:     TargetInt8ConvRot,
	}); err != nil {
		t.Fatalf("ConvertModel: %v", err)
	}

	mergedPath := filepath.Join(t.TempDir(), "merged.safetensors")
	if _, err := ConvertModel(ConvertOptions{
		InputShards: rotShardPaths(),
		OutputPath:  mergedPath,
		Default:     TargetInt8ConvRot,
	}); err != nil {
		t.Fatalf("ConvertModel (merged): %v", err)
	}

	t.Run("output dir has exactly the 2 shards + index", func(t *testing.T) {
		entries, err := os.ReadDir(outDir)
		if err != nil {
			t.Fatalf("reading output dir: %v", err)
		}
		got := make([]string, 0, len(entries))
		for _, e := range entries {
			got = append(got, e.Name())
		}
		want := []string{multiShard1, multiShard2, fixtureIndexName}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("output dir = %v, want exactly %v", got, want)
		}
	})

	t.Run("per-shard headers: row-scale siblings before owners", func(t *testing.T) {
		// Shard 1: rot.a [128,2] -> 128 rows -> 512B of F32 row scales
		// before the 256B I8 owner.
		h1 := readOutShardHeader(t, outDir, multiShard1)
		checkOutHeader(t, h1, []outEntry{
			{rotA + ".scale", DTypeF32, [2]int64{0, 512}},
			{rotA, DTypeI8, [2]int64{512, 768}},
		})
		if !reflect.DeepEqual(h1.Tensors[0].Info.Shape, []int64{128}) {
			t.Errorf("rot.a.scale shape = %v, want [128] (one F32 per row)", h1.Tensors[0].Info.Shape)
		}
		if !reflect.DeepEqual(h1.Tensors[1].Info.Shape, []int64{128, 2}) {
			t.Errorf("rot.a shape = %v, want [128,2] (owner shape preserved)", h1.Tensors[1].Info.Shape)
		}

		// Shard 2: rot.b [2,128] -> 2 rows -> 8B of row scales before the
		// 256B I8 owner.
		h2 := readOutShardHeader(t, outDir, multiShard2)
		checkOutHeader(t, h2, []outEntry{
			{rotB + ".scale", DTypeF32, [2]int64{0, 8}},
			{rotB, DTypeI8, [2]int64{8, 264}},
		})
		if !reflect.DeepEqual(h2.Tensors[0].Info.Shape, []int64{2}) {
			t.Errorf("rot.b.scale shape = %v, want [2] (one F32 per row)", h2.Tensors[0].Info.Shape)
		}
		if !reflect.DeepEqual(h2.Tensors[1].Info.Shape, []int64{2, 128}) {
			t.Errorf("rot.b shape = %v, want [2,128] (owner shape preserved)", h2.Tensors[1].Info.Shape)
		}
	})

	t.Run("data bytes identical to merged output", func(t *testing.T) {
		checkShardsMatchMerged(t, outDir, mergedPath, inIdx)
	})

	t.Run("index: owners + scales in owner shards, file-order keys, total_size", func(t *testing.T) {
		outIdx, err := LoadIndex(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("LoadIndex (output): %v", err)
		}
		want := map[string]string{
			rotA + ".scale": multiShard1,
			rotA:            multiShard1,
			rotB + ".scale": multiShard2,
			rotB:            multiShard2,
		}
		if !reflect.DeepEqual(outIdx.WeightMap, want) {
			t.Errorf("output weight_map = %v, want %v", outIdx.WeightMap, want)
		}
		// Pinned: 512 (rot.a row scales) + 256 (rot.a) + 8 (rot.b row
		// scales) + 256 (rot.b) = sum of the per-shard data bytes.
		if got := outIdx.Metadata["total_size"]; got != float64(1032) {
			t.Errorf("total_size = %v, want 1032 (pinned)", got)
		}
		outRaw, err := os.ReadFile(filepath.Join(outDir, fixtureIndexName))
		if err != nil {
			t.Fatalf("reading output index: %v", err)
		}
		// Key order = file order: before-sibs precede their owners.
		got := weightMapKeyOrder(t, outRaw)
		wantOrder := []string{rotA + ".scale", rotA, rotB + ".scale", rotB}
		if !reflect.DeepEqual(got, wantOrder) {
			t.Errorf("output weight_map key order = %v, want %v (file order)", got, wantOrder)
		}
	})

	t.Run("output dir round-trips through DiscoverShards", func(t *testing.T) {
		shards, idx, err := DiscoverShards(outDir)
		if err != nil {
			t.Fatalf("DiscoverShards(outDir): %v", err)
		}
		if idx == nil {
			t.Fatal("expected the written index to drive discovery")
		}
		want := []string{filepath.Join(outDir, multiShard1), filepath.Join(outDir, multiShard2)}
		if !reflect.DeepEqual(shards, want) {
			t.Errorf("discovered shards = %v, want %v", shards, want)
		}
	})

	t.Run("target-none round-trip is byte-identical to the merged output", func(t *testing.T) {
		shards, idx, err := DiscoverShards(outDir)
		if err != nil {
			t.Fatalf("DiscoverShards(outDir): %v", err)
		}
		rtPath := filepath.Join(t.TempDir(), "roundtrip.safetensors")
		if _, err := ConvertModel(ConvertOptions{
			InputShards: shards,
			InputIndex:  idx,
			OutputPath:  rtPath,
			Default:     TargetNone,
		}); err != nil {
			t.Fatalf("ConvertModel (round-trip): %v", err)
		}
		rt, err := os.ReadFile(rtPath)
		if err != nil {
			t.Fatalf("reading round-trip output: %v", err)
		}
		merged, err := os.ReadFile(mergedPath)
		if err != nil {
			t.Fatalf("reading merged output: %v", err)
		}
		if !bytes.Equal(rt, merged) {
			t.Errorf("target-none round-trip of the output dir differs from the merged output (%d vs %d bytes)", len(rt), len(merged))
		}
	})
}

// TestConvertModelMultiFileNew4BitTargets is the multi-file-output shape
// of TestConvertModelMultiFileInt8 for mxfp4, nvfp4, and int4 on the
// multi fixture: pinned per-shard headers (vector-scale siblings before
// their owners, int4's scalar scale after), index entries for every
// sibling in the owner's shard with file-order keys, a summed total_size,
// and per-tensor byte identity with the merged output.
func TestConvertModelMultiFileNew4BitTargets(t *testing.T) {
	inIdx, err := LoadIndex(filepath.Join(fixtureDir, fixtureIndexName))
	if err != nil {
		t.Fatalf("LoadIndex: %v", err)
	}

	cases := []struct {
		name      string
		target    TargetKind
		shard1    []outEntry
		shard2    []outEntry
		weightMap map[string]string
		keyOrder  []string
		totalSize float64
	}{
		{
			name:   "mxfp4",
			target: TargetMxFP4,
			shard1: []outEntry{
				{nameUpProj + ".block_scale", DTypeU8, [2]int64{0, 1}},
				{nameUpProj, DTypeU8, [2]int64{1, 5}},
				{nameQProj + ".block_scale", DTypeU8, [2]int64{5, 6}},
				{nameQProj, DTypeU8, [2]int64{6, 8}},
			},
			shard2: []outEntry{
				{nameNorm + ".block_scale", DTypeU8, [2]int64{0, 1}},
				{nameNorm, DTypeU8, [2]int64{1, 3}},
				{namePosIDs, DTypeI32, [2]int64{3, 19}},
			},
			weightMap: map[string]string{
				nameUpProj + ".block_scale": multiShard1,
				nameUpProj:                  multiShard1,
				nameQProj + ".block_scale":  multiShard1,
				nameQProj:                   multiShard1,
				nameNorm + ".block_scale":   multiShard2,
				nameNorm:                    multiShard2,
				namePosIDs:                  multiShard2,
			},
			keyOrder: []string{
				nameUpProj + ".block_scale", nameUpProj,
				nameQProj + ".block_scale", nameQProj,
				nameNorm + ".block_scale", nameNorm,
				namePosIDs,
			},
			totalSize: 27, // (1+4)+(1+2) + (1+2)+16
		},
		{
			name:   "nvfp4",
			target: TargetNVFP4,
			shard1: []outEntry{
				{nameUpProj + ".global_scale", DTypeF32, [2]int64{0, 4}},
				{nameUpProj + ".block_scale", DTypeF8E4M3, [2]int64{4, 5}},
				{nameUpProj, DTypeU8, [2]int64{5, 9}},
				{nameQProj + ".global_scale", DTypeF32, [2]int64{9, 13}},
				{nameQProj + ".block_scale", DTypeF8E4M3, [2]int64{13, 14}},
				{nameQProj, DTypeU8, [2]int64{14, 16}},
			},
			shard2: []outEntry{
				{nameNorm + ".global_scale", DTypeF32, [2]int64{0, 4}},
				{nameNorm + ".block_scale", DTypeF8E4M3, [2]int64{4, 5}},
				{nameNorm, DTypeU8, [2]int64{5, 7}},
				{namePosIDs, DTypeI32, [2]int64{7, 23}},
			},
			weightMap: map[string]string{
				nameUpProj + ".global_scale": multiShard1,
				nameUpProj + ".block_scale":  multiShard1,
				nameUpProj:                   multiShard1,
				nameQProj + ".global_scale":  multiShard1,
				nameQProj + ".block_scale":   multiShard1,
				nameQProj:                    multiShard1,
				nameNorm + ".global_scale":   multiShard2,
				nameNorm + ".block_scale":    multiShard2,
				nameNorm:                     multiShard2,
				namePosIDs:                   multiShard2,
			},
			keyOrder: []string{
				nameUpProj + ".global_scale", nameUpProj + ".block_scale", nameUpProj,
				nameQProj + ".global_scale", nameQProj + ".block_scale", nameQProj,
				nameNorm + ".global_scale", nameNorm + ".block_scale", nameNorm,
				namePosIDs,
			},
			totalSize: 39, // (4+1+4)+(4+1+2) + (4+1+2)+16
		},
		{
			name:   "int4",
			target: TargetInt4,
			shard1: []outEntry{
				{nameUpProj, DTypeU8, [2]int64{0, 4}},
				{nameUpProj + ".scale", DTypeF32, [2]int64{4, 8}},
				{nameQProj, DTypeU8, [2]int64{8, 10}},
				{nameQProj + ".scale", DTypeF32, [2]int64{10, 14}},
			},
			shard2: []outEntry{
				{nameNorm, DTypeU8, [2]int64{0, 2}},
				{nameNorm + ".scale", DTypeF32, [2]int64{2, 6}},
				{namePosIDs, DTypeI32, [2]int64{6, 22}},
			},
			weightMap: map[string]string{
				nameUpProj:            multiShard1,
				nameUpProj + ".scale": multiShard1,
				nameQProj:             multiShard1,
				nameQProj + ".scale":  multiShard1,
				nameNorm:              multiShard2,
				nameNorm + ".scale":   multiShard2,
				namePosIDs:            multiShard2,
			},
			keyOrder: []string{
				nameUpProj, nameUpProj + ".scale",
				nameQProj, nameQProj + ".scale",
				nameNorm, nameNorm + ".scale",
				namePosIDs,
			},
			totalSize: 36, // (4+4)+(2+4) + (2+4)+16
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			outDir := t.TempDir()
			if _, err := ConvertModel(ConvertOptions{
				InputShards: multiShardPaths(),
				InputIndex:  inIdx,
				OutputDir:   outDir,
				Default:     tc.target,
			}); err != nil {
				t.Fatalf("ConvertModel: %v", err)
			}

			mergedPath := filepath.Join(t.TempDir(), "merged.safetensors")
			if _, err := ConvertModel(ConvertOptions{
				InputShards: multiShardPaths(),
				OutputPath:  mergedPath,
				Default:     tc.target,
			}); err != nil {
				t.Fatalf("ConvertModel (merged): %v", err)
			}

			t.Run("output dir has exactly the 2 shards + index", func(t *testing.T) {
				entries, err := os.ReadDir(outDir)
				if err != nil {
					t.Fatalf("reading output dir: %v", err)
				}
				got := make([]string, 0, len(entries))
				for _, e := range entries {
					got = append(got, e.Name())
				}
				want := []string{multiShard1, multiShard2, fixtureIndexName}
				if !reflect.DeepEqual(got, want) {
					t.Errorf("output dir = %v, want exactly %v", got, want)
				}
			})

			t.Run("per-shard headers", func(t *testing.T) {
				checkOutHeader(t, readOutShardHeader(t, outDir, multiShard1), tc.shard1)
				checkOutHeader(t, readOutShardHeader(t, outDir, multiShard2), tc.shard2)
			})

			t.Run("index: siblings in owner shards, key order, total_size", func(t *testing.T) {
				outIdx, err := LoadIndex(filepath.Join(outDir, fixtureIndexName))
				if err != nil {
					t.Fatalf("LoadIndex (output): %v", err)
				}
				if !reflect.DeepEqual(outIdx.WeightMap, tc.weightMap) {
					t.Errorf("output weight_map = %v, want %v", outIdx.WeightMap, tc.weightMap)
				}
				if got := outIdx.Metadata["total_size"]; got != tc.totalSize {
					t.Errorf("total_size = %v, want %v (sum of per-shard data bytes)", got, tc.totalSize)
				}
				outRaw, err := os.ReadFile(filepath.Join(outDir, fixtureIndexName))
				if err != nil {
					t.Fatalf("reading output index: %v", err)
				}
				got := weightMapKeyOrder(t, outRaw)
				if !reflect.DeepEqual(got, tc.keyOrder) {
					t.Errorf("output weight_map key order = %v, want %v (file order)", got, tc.keyOrder)
				}
			})

			t.Run("data bytes identical to merged output", func(t *testing.T) {
				checkShardsMatchMerged(t, outDir, mergedPath, inIdx)
			})

			t.Run("output dir is a loadable model directory", func(t *testing.T) {
				shards, idx, err := DiscoverShards(outDir)
				if err != nil {
					t.Fatalf("DiscoverShards(outDir): %v", err)
				}
				if idx == nil {
					t.Fatal("expected the written index to drive discovery")
				}
				want := []string{filepath.Join(outDir, multiShard1), filepath.Join(outDir, multiShard2)}
				if !reflect.DeepEqual(shards, want) {
					t.Errorf("discovered shards = %v, want %v", shards, want)
				}
			})
		})
	}
}

// TestConvertModelConfigMixedTargets runs one synthetic model through
// ConvertFile with a config that resolves six different tensors to six
// different targets (int8_convrot, mxfp4, nvfp4, int4, none, and the
// config default fp8_e4m3), and pins each tensor's output dtype, sibling
// layout, and report fields (scale, note, skip reason) to its resolved
// target.
func TestConvertModelConfigMixedTargets(t *testing.T) {
	convVals := make([]float32, 256) // a multiple of the ConvRot group size
	for i := range convVals {
		convVals[i] = float32(i%13-6) * 0.25
	}
	convVals[10] = 12.0
	mxVals := make([]float32, 64)
	for i := range mxVals {
		mxVals[i] = float32(i%5-2) * 0.5
	}
	nvVals := make([]float32, 48)
	for i := range nvVals {
		nvVals[i] = 0.5
	}
	nvVals[0] = 2688 // M = 6*448 -> global scale alpha = exactly 1
	i4Vals := make([]float32, 32)
	for i := range i4Vals {
		i4Vals[i] = 1.0
	}
	i4Vals[0] = 14.0 // maxAbs 14 -> int4 scale 14/7 = 2.0
	skipVals := make([]float32, 10)
	defVals := make([]float32, 32)
	for i := range defVals {
		defVals[i] = float32(i%7-3) * 0.1
	}
	in := writeF32Shard(t,
		f32Tensor{name: "w.convrot", vals: convVals},
		f32Tensor{name: "w.mx", vals: mxVals},
		f32Tensor{name: "w.nv", vals: nvVals},
		f32Tensor{name: "w.i4", vals: i4Vals},
		f32Tensor{name: "w.skip", vals: skipVals},
		f32Tensor{name: "w.def", vals: defVals},
	)

	cfgPath := filepath.Join(t.TempDir(), "config.json")
	cfg := `{
	  "default": "fp8_e4m3",
	  "rules": [
	    { "match": "w.convrot", "dtype": "int8_convrot" },
	    { "match": "w.mx", "dtype": "mxfp4" },
	    { "match": "w.nv", "dtype": "nvfp4" },
	    { "match": "w.i4", "dtype": "int4" },
	    { "pattern": "^w\\.skip$", "dtype": "none" }
	  ]
}`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	cfgObj, err := LoadConfig(cfgPath)
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}

	outPath := filepath.Join(t.TempDir(), "out.safetensors")
	stats, err := ConvertFile(ConvertOptions{
		InputPath:  in,
		OutputPath: outPath,
		Config:     cfgObj,
	})
	if err != nil {
		t.Fatalf("ConvertFile: %v", err)
	}

	out, err := os.Open(outPath)
	if err != nil {
		t.Fatalf("opening output: %v", err)
	}
	defer out.Close()
	outHeader, _, err := ReadHeader(out)
	if err != nil {
		t.Fatalf("reading output header: %v", err)
	}

	// One sibling layout per resolved target, in input tensor order:
	// convrot's (1-D -> one row -> scalar) F32 scale before the I8 owner;
	// mxfp4's E8M0 block scales (64/32 = 2) before the packed owner;
	// nvfp4's F32 global scale + E4M3 block scales (48/16 = 3) before the
	// packed owner; int4's packed owner followed by its scalar F32 scale;
	// the "none" tensor passthrough at F32; the default fp8_e4m3 tensor.
	checkOutHeader(t, outHeader, []outEntry{
		{"w.convrot.scale", DTypeF32, [2]int64{0, 4}},
		{"w.convrot", DTypeI8, [2]int64{4, 260}},
		{"w.mx.block_scale", DTypeU8, [2]int64{260, 262}},
		{"w.mx", DTypeU8, [2]int64{262, 294}},
		{"w.nv.global_scale", DTypeF32, [2]int64{294, 298}},
		{"w.nv.block_scale", DTypeF8E4M3, [2]int64{298, 301}},
		{"w.nv", DTypeU8, [2]int64{301, 325}},
		{"w.i4", DTypeU8, [2]int64{325, 341}},
		{"w.i4.scale", DTypeF32, [2]int64{341, 345}},
		{"w.skip", DTypeF32, [2]int64{345, 385}},
		{"w.def", DTypeF8E4M3, [2]int64{385, 417}},
	})

	// Report fields per resolved target: only convrot and nvfp4 carry a
	// note; only int4 (like int8) carries a per-tensor scale; only the
	// "none" tensor is skipped.
	wantStats := []struct {
		name       string
		toDType    DType
		scale      float32
		note       string
		skippedWhy bool
	}{
		{"w.convrot", DTypeI8, 0, "convrot rows=1", false},
		{"w.mx", DTypeU8, 0, "", false},
		{"w.nv", DTypeU8, 0, "nvfp4 scale=1", false},
		{"w.i4", DTypeU8, 2.0, "", false},
		{"w.skip", DTypeF32, 0, "", true},
		{"w.def", DTypeF8E4M3, 0, "", false},
	}
	if len(stats) != len(wantStats) {
		t.Fatalf("got %d stats, want %d", len(stats), len(wantStats))
	}
	for i, w := range wantStats {
		s := stats[i]
		if s.Name != w.name {
			t.Errorf("stat[%d].Name = %q, want %q", i, s.Name, w.name)
			continue
		}
		if s.ToDType != w.toDType {
			t.Errorf("stat (%s).ToDType = %v, want %v", s.Name, s.ToDType, w.toDType)
		}
		if s.Scale != w.scale {
			t.Errorf("stat (%s).Scale = %v, want %v", s.Name, s.Scale, w.scale)
		}
		if s.Note != w.note {
			t.Errorf("stat (%s).Note = %q, want %q", s.Name, s.Note, w.note)
		}
		if (s.SkippedWhy != "") != w.skippedWhy {
			t.Errorf("stat (%s).SkippedWhy = %q, want non-empty = %v", s.Name, s.SkippedWhy, w.skippedWhy)
		}
	}
}

func TestConvertModelMultiFileErrors(t *testing.T) {
	t.Run("OutputPath and OutputDir both set", func(t *testing.T) {
		_, err := ConvertModel(ConvertOptions{
			InputShards: multiShardPaths(),
			OutputPath:  filepath.Join(t.TempDir(), "a.safetensors"),
			OutputDir:   t.TempDir(),
			Default:     TargetNone,
		})
		if err == nil || !strings.Contains(err.Error(), "mutually exclusive") {
			t.Fatalf("expected mutually-exclusive error, got %v", err)
		}
	})

	t.Run("multi-file output without input index", func(t *testing.T) {
		_, err := ConvertModel(ConvertOptions{
			InputShards: multiShardPaths(),
			OutputDir:   t.TempDir(),
			Default:     TargetNone,
		})
		if err == nil || !strings.Contains(err.Error(), "requires an input index") {
			t.Fatalf("expected missing-index error, got %v", err)
		}
	})
}
